In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('/content/test_data_cleaning.csv')

In [3]:
df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about  # earthquake is different cities,...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN     Apocalypse lighting .   # Spokane  # wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [4]:
df.shape

(3263, 4)

**TEXT PREPROCESSING**

**LOWERCASING**

In [6]:
df['text'].str.lower()

0                      just happened a terrible car crash
1       heard about  # earthquake is different cities,...
2       there is a forest fire at spot pond, geese are...
3          apocalypse lighting .   # spokane  # wildfires
4           typhoon soudelor kills 28 in china and taiwan
                              ...                        
3258    earthquake safety los angeles  safety fastener...
3259    storm in ri worse than last hurricane .  my ci...
3260                    green line derailment in chicago 
3261      meg issues hazardous weather outlook  ( hwo )  
3262     # city of calgary has activated its municipal...
Name: text, Length: 3263, dtype: object

**REMOVING HTML TAGS**

In [7]:
import re 
def remove_html_tags(text):
  pattern= re.compile('<.*?>')
  return pattern.sub(r'',text)

In [8]:
df['text'].apply(remove_html_tags)

0                      Just happened a terrible car crash
1       Heard about  # earthquake is different cities,...
2       there is a forest fire at spot pond, geese are...
3          Apocalypse lighting .   # Spokane  # wildfires
4           Typhoon Soudelor kills 28 in China and Taiwan
                              ...                        
3258    EARTHQUAKE SAFETY LOS ANGELES  SAFETY FASTENER...
3259    Storm in RI worse than last hurricane .  My ci...
3260                    Green Line derailment in Chicago 
3261      MEG issues Hazardous Weather Outlook  ( HWO )  
3262     # City of Calgary has activated its Municipal...
Name: text, Length: 3263, dtype: object

**REMOVING STOP WORDS**

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [14]:
def remove_stopwords(text):
  new_text=[]
  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
        new_text.append(word)
        x= new_text[:]
        new_text.clear()
        return " ".join(x)
        

In [15]:
df['text'].apply(remove_stopwords)

0             Just
1            Heard
2           forest
3       Apocalypse
4          Typhoon
           ...    
3258    EARTHQUAKE
3259         Storm
3260         Green
3261           MEG
3262             #
Name: text, Length: 3263, dtype: object

**FEATURE EXTRACTION**

**BAG OF WORDS OR UNIGRAM TECHNIQUE**

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv= CountVectorizer()

In [20]:
bow= cv.fit_transform(df['text'])

In [22]:
print(cv.vocabulary_)

{'just': 4828, 'happened': 3990, 'terrible': 8787, 'car': 1659, 'crash': 2253, 'heard': 4071, 'about': 392, 'earthquake': 2897, 'is': 4614, 'different': 2626, 'cities': 1910, 'stay': 8421, 'safe': 7637, 'everyone': 3137, 'there': 8862, 'forest': 3502, 'fire': 3393, 'at': 874, 'spot': 8342, 'pond': 6803, 'geese': 3698, 'are': 788, 'fleeing': 3437, 'across': 434, 'the': 8827, 'street': 8486, 'cannot': 1637, 'save': 7710, 'them': 8847, 'all': 599, 'apocalypse': 744, 'lighting': 5199, 'spokane': 8330, 'wildfires': 9734, 'typhoon': 9245, 'soudelor': 8251, 'kills': 4927, '28': 155, 'in': 4434, 'china': 1857, 'and': 680, 'taiwan': 8683, 'we': 9622, 'shaking': 7902, 'it': 4637, 'an': 670, 'they': 8876, 'probably': 6935, 'still': 8451, 'show': 8000, 'more': 5821, 'life': 5190, 'than': 8817, 'arsenal': 814, 'did': 2614, 'yesterday': 9953, 'eh': 2953, 'hey': 4126, 'how': 4284, 'you': 9965, 'what': 9684, 'nice': 6078, 'hat': 4025, 'fuck': 3598, 'off': 6251, 'no': 6114, 'do': 2714, 'not': 6156, 'li

In [23]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


**BAG OF NGRAMS**

**BIGRAMS**

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv= CountVectorizer(ngram_range=(2,2))

In [27]:
bow= cv.fit_transform(df['text'])

In [30]:
print(cv.vocabulary_)

{'just happened': 14052, 'happened terrible': 10987, 'terrible car': 24332, 'car crash': 5123, 'heard about': 11384, 'about earthquake': 682, 'earthquake is': 7873, 'is different': 13301, 'different cities': 7245, 'cities stay': 5627, 'stay safe': 23504, 'safe everyone': 21669, 'there is': 25541, 'is forest': 13331, 'forest fire': 9668, 'fire at': 9053, 'at spot': 2717, 'spot pond': 23353, 'pond geese': 20047, 'geese are': 10147, 'are fleeing': 2259, 'fleeing across': 9286, 'across the': 823, 'the street': 25302, 'street cannot': 23732, 'cannot save': 5071, 'save them': 21818, 'them all': 25462, 'apocalypse lighting': 2163, 'lighting spokane': 14830, 'spokane wildfires': 23336, 'typhoon soudelor': 27171, 'soudelor kills': 23207, 'kills 28': 14266, '28 in': 333, 'in china': 12528, 'china and': 5559, 'and taiwan': 1950, 'we are': 28270, 'are shaking': 2312, 'shaking it': 22358, 'it is': 13647, 'is an': 13230, 'an earthquake': 1571, 'they probably': 25620, 'probably still': 20305, 'still 

In [35]:
print(len(cv.vocabulary_))

33455


**TRIGRAM**

In [31]:
cv= CountVectorizer(ngram_range=(3,3))

In [32]:
bow= cv.fit_transform(df['text'])

In [33]:
print(cv.vocabulary_)

{'just happened terrible': 15437, 'happened terrible car': 11712, 'terrible car crash': 26429, 'heard about earthquake': 12231, 'about earthquake is': 663, 'earthquake is different': 8408, 'is different cities': 14414, 'different cities stay': 7713, 'cities stay safe': 6076, 'stay safe everyone': 25563, 'there is forest': 27952, 'is forest fire': 14440, 'forest fire at': 10302, 'fire at spot': 9593, 'at spot pond': 3012, 'spot pond geese': 25410, 'pond geese are': 22072, 'geese are fleeing': 10825, 'are fleeing across': 2473, 'fleeing across the': 9859, 'across the street': 828, 'the street cannot': 27659, 'street cannot save': 25788, 'cannot save them': 5520, 'save them all': 23833, 'apocalypse lighting spokane': 2371, 'lighting spokane wildfires': 16256, 'typhoon soudelor kills': 30032, 'soudelor kills 28': 25267, 'kills 28 in': 15658, '28 in china': 327, 'in china and': 13444, 'china and taiwan': 6012, 'we are shaking': 31222, 'are shaking it': 2557, 'shaking it is': 24387, 'it is a

In [37]:
print(len(cv.vocabulary_))

33455


**TFIDF- TERM FREQUENCY AND INVERSE DOCUMENT FREQUENCY**

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf= TfidfVectorizer()

In [40]:
tfidf.fit_transform(df['text']).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
print(tfidf.idf_)

[6.25749537 7.99209643 8.39756154 ... 7.70441435 8.39756154 8.39756154]


In [42]:
print(tfidf.get_feature_names_out())

['00' '000' '00am' ... 'ìàekdar' 'ìñ2' 'û¼']
